# Site settings
title: I Love Tall
email: info@ilovetall.com
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: jekyllrb
github_username:  jekyll
description: "I Love Tall - fashion for tall people, modische Langgrössen Bekleidung für grosse Frauen und Männer"
url: "https://www.ilovetall.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# scss files
sass:
  sass_dir: _bootstrap/scss

google_analytics_tracking_id: UA-27462297-2
